### ISSUE TITLE
300BoxMoekaiCrack 有源码吗？

### ISSUE THREAD

**Issue by QGB** [usaginya/mkAppUpInfo#1]
想看。。

我想截获300的聊天信息，不知道怎么下手啊。。

**Comment by usaginya** [comment]
这只是一个提供免费试用300box的付费功能的工具、游戏扩展的功能主要是由300box完成的、而300box的作者另有他人、需要了解游戏扩展的功能需要联系300box的作者

**Comment by QGB** [comment]
别关啊，所以有300BoxMoekaiCrack 的源码吗

**Comment by usaginya** [comment]
@QGB  300BoxMoekaiCrack内没有你所说的截获300消息的功能、我觉得这个源码对你来说不会有帮助、也因为不到主流开发平台的源码。如果你还是确定你需要这个程序的源码、可以打包发到你的Email里
