### ISSUE TITLE
部分站点已经失效

### ISSUE THREAD

**Issue by ivysrono** [usaginya/mkAppUpInfo#5]
阿里云
支付宝
百度网盘
斗鱼（半有效，显示在手机登录上）
CSDN

**Comment by usaginya** [comment]
@ivysrono 伙计，这个是之前我自己修正原作者在grease fork上的脚本bug给自己用的，它已经没用了。现在作者已经更新了，所以你应该去grease fork上更新脚本，而不是这里。
这个项目本来就是放一些杂物和成品，不是真的用来开源，大多数是用来外链使用。为了不再使你产生误会，我会把它从这删除。去安装原作者的脚本吧，祝你好运！

**Comment by usaginya** [comment]
@ivysrono 链接在这：[https://greasyfork.org/zh-CN/scripts/37988](https://greasyfork.org/zh-CN/scripts/37988)

**Comment by ivysrono** [comment]
好吧，thx
